# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

#ActsAsTaggableOn::Tag:
  #fields:
    #default: name
    #form: name
  #order_by:
  #relationships:
  #filters:
  #search: name
  #application: rails-bestpractices.com

AdminUser:
  fields:
    default: first_name, last_name, role, email, status, token, preferences
    form: first_name, last_name, role, email, status, token, preferences
  order_by:
  relationships:
  filters:
  search:
  application: rails-bestpractices.com

Answer:
  fields:
    default: vote_points, question_id, question, user
    form: body, formatted_html, vote_points, question_id, question, user
  order_by: -created_at
  relationships: question, user, votes
  filters:
  search:
  application: rails-bestpractices.com

Comment:
  fields:
    default: user_id, username, email, commentable
    form: body, user_id, username, email
  order_by: -created_at
  relationships: user
  filters:
  search:
  application: rails-bestpractices.com

Drop:
  fields:
    default: title, kind, tag_list, user
    form: title, kind, description, body, formatted_html, tag_list, user
  order_by: -created_at
  relationships: user
  filters:
  search: title
  application: rails-bestpractices.com

Implementation:
  fields:
    default: post_id, post, user
    form: post_id, body, formatted_html, post, user
  order_by: -created_at
  relationships: post, user
  filters:
  search: title
  application: rails-bestpractices.com

Notification:
  fields:
    default: user_id, notifierable_id, read, user
    form: user_id, notifierable_id, read, user
  order_by: -created_at
  relationships: user
  filters:
  search:
  application: rails-bestpractices.com

NotificationSetting:
  fields:
    default: name, value, user_id, user
    form: name, value, user_id, user
  order_by:
  relationships: user
  filters:
  search: name
  application: rails-bestpractices.com

Page:
  fields:
    default: name
    form: name, body
  order_by: -created_at
  redlationships:
  filters:
  search: name
  application: rails-bestpractices.com

Post:
  fields:
    default: title, comments_count, vote_points, view_count, tag_list, user, implemented
    form: title, body, formatted_html, description, comments_count, vote_points, view_count, tag_list, user, implemented
  order_by: -created_at
  relationships: base_tags, comments, implementation, tag_taggings, taggings, tags, user, votes
  filters:
  search: title
  application: rails-bestpractices.com

Question:
  fields:
    default: title, vote_points, view_count, answers_count, user
    form: title, body, formatted_html, vote_points, view_count, answers_count, user
  order_by: -created_at
  relationships: answers, base_tags, tag_taggings, taggings, tags, user, votes
  filters:
  search: title
  application: rails-bestpractices.com

User:
  fields:
    default: login, email, url, developer, posts_count, implementations_count, comments_count, votes_count, questions_count, answers_count
    form: login, email, url, developer, posts_count, implementations_count, comments_count, votes_count, questions_count, answers_count
  order_by: -created_at
  relationships: comments, implementations, posts, votes, questions, answers
  filters:
  search: login
  application: rails-bestpractices.com

Vote:
  fields:
    default: like, user, voteable
    form: like, user, voteable
  order_by: -created_at
  relationships: voteable, user
  filters:
  search:
  application: rails-bestpractices.com
