# Typus Roles Configuration File
#
# Use the README file as a reference to customize settings.

admin:
  #ActsAsTaggableOn::Tag: read, delete
  AdminUser: create, read, update, delete
  Answer: create, read, update, delete
  Comment: create, read, update, delete
  Implementation: create, read, update, delete
  Page: create, read, update, delete
  Post: create, read, update, delete
  Question: create, read, update, delete
  User: create, read, update, delete
  Vote: create, read, update, delete
